# secret-from-manifest-base64.yaml
# This demonstrates the classic, declarative way to create a Secret.
# The 'data' field requires all values to be manually base64 encoded.

apiVersion: v1
kind: Secret
metadata:
  name: secret-from-manifest-base64
type: Opaque # The default type for arbitrary key-value secrets.
data:
  # The key for our secret.
  SECRET_BASE64_VAR: "dGhpcy1pcy1hLWJhc2U2NC1zZWNyZXQ=" # The string "this-is-a-base64-secret" encoded in base64.
