# https://taskfile.dev

version: "3"

vars:
  CONTAINER_ENGINE: docker
  KIND_CONFIG: ./kind-config.yaml

includes:
  01-setup:
    taskfile: ./tasks/01-setup.yml
    dir: .
  02-pod:
    taskfile: ./tasks/02-pods.yml
    dir: .
  03-deployment:
    taskfile: ./tasks/03-deployments.yml
    dir: .
  04-configmap:
    taskfile: ./tasks/04-configmaps.yml
    dir: .
  05-secret:
    taskfile: ./tasks/05-secrets.yml
    dir: .
  06-volume:
    taskfile: ./tasks/06-volumes.yml
    dir: .
  07-networking:
    taskfile: ./tasks/07-networking.yml
    dir: .
  08-advanced-pods:
    taskfile: ./tasks/08-advanced-pods.yml
    dir: .
  09-cluster-organization:
    taskfile: ./tasks/09-cluster-organization.yml
    dir: .
  10-specialized-workloads:
    taskfile: ./tasks/10-specialized-workloads.yml
    dir: .

tasks:
  default:
    desc: "Lists all available tasks from all included files."
    silent: true
    cmds:
      - task --list-all
