# https://taskfile.dev

version: "3"

vars:
  CONTAINER_ENGINE: docker
  KIND_CONFIG: ./kind-config.yaml

includes:
  01-setup:
    taskfile: ./tasks/01-setup.yml
    dir: ./tasks
  02-pod:
    taskfile: ./tasks/02-pods.yml
    dir: ./tasks
  03-deployment:
    taskfile: ./tasks/03-deployments.yml
    dir: ./tasks

tasks:
  default:
    desc: "Lists all available tasks from all included files."
    silent: true
    cmds:
      - task --list-all
