# https://taskfile.dev

version: '3'

vars:
  CONTAINER_ENGINE: docker # Can be set to 'podman' as well
  KIND_CONFIG: ./kind-config.yaml

tasks:
  install-docker:
    desc: "Installs Docker using the official Docker repository."
    cmds:
      - |
        echo "Installing Docker..."
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        echo "Docker installed successfully."
        docker --version

        echo "Adding current user (${USER}) to the 'docker' group to avoid permission errors..."
        sudo usermod -aG docker ${USER}
        
        echo ""
        echo "#########################################################################################"
        echo "#"
        echo "#  ACTION REQUIRED: For group changes to apply, you must either:"
        echo "#  1. Log out and log back in."
        echo "#  2. Or run the command: newgrp docker"
        echo "#"
        echo "#########################################################################################"
    preconditions:
      - sh: '[ "{{.CONTAINER_ENGINE}}" = "docker" ]'
        msg: "CONTAINER_ENGINE is not set to docker."
      - sh: "! command -v docker"
        msg: "Docker is already installed."

  install-podman:
    desc: "Installs Podman from the default Ubuntu repositories."
    cmds:
      - |
        echo "Installing Podman..."
        sudo apt-get update
        sudo apt-get install -y podman
        echo "Podman installed successfully."
        podman --version
    preconditions:
      - sh: '[ "{{.CONTAINER_ENGINE}}" = "podman" ]'
        msg: "CONTAINER_ENGINE is not set to podman."
      - sh: "! command -v podman"
        msg: "Podman is already installed."

  install-kind:
    desc: "Installs Kind (Kubernetes in Docker)."
    cmds:
      - |
        echo "Installing Kind..."
        curl -Lo ./kind "https://kind.sigs.k8s.io/dl/v0.20.0/kind-$(uname)-amd64"
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind
        echo "Kind installed successfully."
        kind --version
    preconditions:
      - sh: "! command -v kind"
        msg: "Kind is already installed."

  install-kubectl:
    desc: "Installs kubectl, the Kubernetes command-line tool."
    cmds:
      - |
        echo "Installing kubectl..."
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        rm kubectl
        echo "kubectl installed successfully."
        kubectl version --client
    preconditions:
      - sh: "! command -v kubectl"
        msg: "kubectl is already installed."

  setup-kube:
    desc: "Sets up the complete Kubernetes environment based on the specified CONTAINER_ENGINE."
    deps:
      - task: install-{{.CONTAINER_ENGINE}}
      - task: install-kind
      - task: install-kubectl
    cmds:
      - echo "Kubernetes setup complete with {{.CONTAINER_ENGINE}}, Kind, and kubectl."

  cluster-up:
    desc: "Creates a Kind cluster using the local kind-config.yaml file."
    cmds:
      - kind create cluster --config {{.KIND_CONFIG}}
    preconditions:
      - sh: '[ -f {{.KIND_CONFIG}} ]'
        msg: "The Kind config file is missing. Please ensure '{{.KIND_CONFIG}}' exists."
      - sh: '!(kind get clusters | grep -q "^kind$")'
        msg: "A Kind cluster named 'kind' already exists. Use 'task cluster-down' to delete it first."

  cluster-down:
    desc: "Deletes the local Kind cluster."
    cmds:
      - kind delete cluster
    preconditions:
      - sh: '(kind get clusters | grep -q "^kind$")'
        msg: "No Kind cluster named 'kind' was found."

# --- Kubernetes Resource Management ---
  apply-nginx-pod:
    desc: "Applies the nginx-pod.yaml manifest to create the pod."
    cmds:
      - kubectl apply -f nginx-pod.yaml

  delete-nginx-pod:
    desc: "Deletes the nginx-pod using the manifest file."
    cmds:
      - kubectl delete -f nginx-pod.yaml

  get-pods:
    desc: "Lists all pods in the current namespace with extra details."
    cmds:
      - kubectl get pods -o wide

  get-replicasets:
    desc: "Lists all ReplicaSets in the current namespace."
    cmds:
      - kubectl get replicasets

  get-deployments:
    desc: "Lists all Deployments in the current namespace."
    cmds:
      - kubectl get deployments

  get-all:
    desc: "A convenience command to see the most common running resources."
    cmds:
      - kubectl get deployments,replicasets,pods,svc

  describe-pod:
    desc: "Shows detailed information about the nginx-pod."
    cmds:
      - kubectl describe pod nginx-pod

  logs-pod:
    desc: "Streams the logs from the nginx-pod."
    cmds:
      # The '-f' flag follows the log stream, similar to 'tail -f'
      - kubectl logs -f nginx-pod
  
  default:
    desc: "Shows usage information."
    silent: true
    cmds:
      - |
        echo "Usage: task [command]"
        echo ""
        echo "Cluster Management:"
        echo "  setup-kube:      Installs the specified container engine, Kind, and kubectl."
        echo "  cluster-up:      Creates a Kind cluster using the local config file."
        echo "  cluster-down:    Deletes the local Kind cluster."
        echo ""
        echo "Kubernetes Commands:"
        echo "  apply-nginx-pod: Creates the simple Nginx pod."
        echo "  delete-nginx-pod: Deletes the Nginx pod."
        echo "  get-pods:        Lists all pods."
        echo "  get-replicasets: Lists all ReplicaSets."
        echo "  get-deployments: Lists all Deployments."
        echo "  get-all:         Lists the most common resources (Deployments, Pods, Services)."
        echo "  describe-pod:    Shows detailed information about the Nginx pod."
        echo "  logs-pod:        Streams the logs from the Nginx pod."
        echo ""
        echo "Individual Installers:"
        echo "  install-docker:  Installs Docker."
        echo "  install-podman:  Installs Podman."
        echo "  install-kind:    Installs Kind."
        echo "  install-kubectl: Installs kubectl."